preferred_endpoint: openai

endpoints:
  

  openai:
    api_key_env: OPENAI_API_KEY
    api_endpoint_env: OPENAI_ENDPOINT
    llm_type: openai
    models:
      high: gpt-4.1
      low: gpt-4.1-mini

  anthropic:
    api_key_env: ANTHROPIC_API_KEY
    llm_type: anthropic
    models:
      high: claude-3-7-sonnet-latest
      low: claude-3-5-haiku-latest

  gemini:
    api_key_env: GEMINI_API_KEY
    llm_type: gemini
    models:
      high: gemini-2.0-flash
      low: gemini-2.0-flash

  

  

  huggingface:
    api_key_env: HF_TOKEN
    llm_type: huggingface
    models:
      high: Qwen/Qwen2.5-72B-Instruct
      low: Qwen/Qwen2.5-Coder-7B-Instruct

  