preferred_provider: huggingFace

providers:
  openai:
    api_key_env: OPENAI_API_KEY
    api_endpoint_env: OPENAI_ENDPOINT
    model: text-embedding-3-small

  huggingFace:
    api_key_env: HF_API_KEY
    model: all-MiniLM-L6-v2
    dimensions: 384
