repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1024']  # 1MB limit to prevent large files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.9
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format

  - repo: local
    hooks:
      - id: uv-sync
        name: UV Sync
        entry: uv sync --dev
        language: system
        pass_filenames: false
        always_run: true

      - id: pytest
        name: pytest
        entry: uv run pytest -n auto
        language: system
        pass_filenames: false
        always_run: true

      - id: test-coverage
        name: Test Coverage
        entry: uv run pytest --cov=core --cov-config=.coveragerc --cov-report=term-missing --cov-fail-under=70
        language: system
        pass_filenames: false
        always_run: true

      - id: mypy
        name: mypy
        entry: uv run mypy
        language: system
        types: [python]
        pass_filenames: false

  - repo: https://github.com/PyCQA/bandit
    rev: '1.8.3'
    hooks:
      - id: bandit
        args: ["-c", "bandit.yaml", "-r", "core"]

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
